FROM nginx:mainline-alpine

# IMPORTANT! #
# run this dockerfile from the parent directory 'web' (contains 'client') #

# define arguments for the build
ARG server_root=/usr/share/nginx/html/rainbow-forest

# add packages
#   - yarn: package manager for app build
RUN apk update && apk add \
  yarn

RUN rm /etc/nginx/conf.d/*
ADD client/root.conf /etc/nginx/conf.d/

# create working directory in which to build app
WORKDIR /usr/src/app

# install dependencies (before source files to utilize caching)
COPY client/package*.json ./
COPY client/yarn.lock ./
RUN yarn install --production

# copy source files and run build
COPY ./client ./client
COPY ./common ./common
RUN cd client && yarn build

# copy build to location to be served by nginx
RUN mkdir -p ${server_root} && cp -r build/. ${server_root}/

# remove working directory to reduce image size
RUN rm -rf /usr/src/app
